language: "perl"

perl:
#  - "5.8"
#  - "5.10"
  - "5.14"
#  - "5.18"
#  - "5.22"

env:
  - COVERALLS=true  DB=mysql

sudo: false

cache:
  apt: false
  directories:
    - $HOME/perl5/perlbrew
    - $HOME/dependencies

addons:
  apt:
    packages:
      - unzip
      - mysql-server-5.5
      - apache2
      - libmysqlclient-dev
      - libpng12-dev
      - libssl-dev
      - openssl
      - mysql-client-5.5
      - mysql-client-core-5.5

before_install:
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
  # - git clone --branch master --depth 1 https://github.com/Ensembl/Bio-HTS
  # - wget https://github.com/bioperl/bioperl-live/archive/release-1-6-924.zip
  # - unzip release-1-6-924.zip
  - export CWD=$PWD
  - export DEPS=$HOME/dependencies
  - mkdir -p $DEPS
  - cd $DEPS
  - $CWD/travisci/get_dependencies.sh
  - cd $CWD

install:
  - export CWD=$PWD
  - export DEPS=$HOME/dependencies
  - export KENT_SRC="$DEPS/kent/src"
  - export HTSLIB_DIR="$DEPS/htslib"
  - export MACHTYPE=$(uname -m)
  - export CFLAGS="-fPIC"
  - echo `ls ~`
  - echo `ls $DEPS`
  - export PERL5LIB=$DEPS/bioperl-live-release-1-6-924:$PERL5LIB
  - cd $DEPS
  - echo `pwd`
  - $CWD/travisci/build_c.sh
  - cd $CWD
  - ldd /home/travis/perl5/perlbrew/perls/5.14/lib/site_perl/5.14.3/x86_64-linux/auto/Bio/DB/BigFile/BigFile.so
  - cpanm --quiet --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
  - cpanm --verbose Bio::DB::BigFile
  - cpanm --installdeps --notest .
  - cpanm --quiet -n Devel::Cover::Report::Coveralls
  - cp travisci/MultiTestDB.conf.travisci  t/MultiTestDB.conf

script: "./travisci/harness.sh"

notifications:
  email:
    on_success: always
    on_failure: always
